services:
  audit:
    container_name: audit-worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    ports:
      - ${AUDIT_WORKER_PORT}:${AUDIT_WORKER_PORT}
    environment:
      - REDIS_URL=${REDIS_URL}
      - AUDIT_QUEUE_NAME=${AUDIT_QUEUE_NAME}
      - AUDIT_CRYPTO_SECRET=${AUDIT_CRYPTO_SECRET}
      - AUDIT_DB_URL=${AUDIT_DB_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - AUDIT_WORKER_PORT=${AUDIT_WORKER_PORT}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${AUDIT_WORKER_PORT}/healthz']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
