# Alertmanager configuration for SMEDREC Audit Server
global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: '${ALERT_FROM_EMAIL}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Templates for alert notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Warning alerts - grouped notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m

    # Database alerts
    - match:
        service: postgres
      receiver: 'database-alerts'

    # Application alerts
    - match:
        service: audit-server
      receiver: 'application-alerts'

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

# Receivers configuration
receivers:
  # Default webhook receiver
  - name: 'web.hook'
    webhook_configs:
      - url: '${WEBHOOK_URL}'
        send_resolved: true
        http_config:
          bearer_token: '${WEBHOOK_TOKEN}'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: '${CRITICAL_ALERT_EMAIL}'
        subject: '[CRITICAL] SMEDREC Audit System Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          Time: {{ .CommonAnnotations.timestamp }}

          View in Grafana: ${GRAFANA_URL}/d/audit-server-overview
        headers:
          Subject: '[CRITICAL] SMEDREC Audit System Alert'

    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: 'Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
        send_resolved: true

    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .CommonAnnotations.summary }}'
        severity: 'critical'

  # Warning alerts - email only
  - name: 'warning-alerts'
    email_configs:
      - to: '${WARNING_ALERT_EMAIL}'
        subject: '[WARNING] SMEDREC Audit System Alert'
        body: |
          Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          Time: {{ .CommonAnnotations.timestamp }}

  # Database specific alerts
  - name: 'database-alerts'
    email_configs:
      - to: '${DBA_EMAIL}'
        subject: '[DATABASE] SMEDREC Audit Database Alert'
        body: |
          Database Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Database: {{ .CommonLabels.database }}
          Instance: {{ .CommonLabels.instance }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

  # Application specific alerts
  - name: 'application-alerts'
    email_configs:
      - to: '${DEV_TEAM_EMAIL}'
        subject: '[APPLICATION] SMEDREC Audit Server Alert'
        body: |
          Application Alert: {{ .GroupLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Service: {{ .CommonLabels.service }}
          Instance: {{ .CommonLabels.instance }}
          Summary: {{ .CommonAnnotations.summary }}
          Description: {{ .CommonAnnotations.description }}

          Logs: ${LOGS_URL}
          Metrics: ${GRAFANA_URL}
